version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - LLM_ENDPOINT=http://ollama:11434/v1/chat/completions
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
